openapi: 3.0.0
info:
  title: Janitri Backend API
  description: API for managing users, patients, and heart rate data.
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User registered successfully
  /login:
    post:
      summary: User login
      responses:
        200:
          description: Login successful
